#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : openstack.nose_plugin
Version  : 0.11
Release  : 9
URL      : https://pypi.python.org/packages/source/o/openstack.nose_plugin/openstack.nose_plugin-0.11.tar.gz
Source0  : https://pypi.python.org/packages/source/o/openstack.nose_plugin/openstack.nose_plugin-0.11.tar.gz
Summary  : openstack run_tests.py style output for nosetests
Group    : Development/Tools
License  : Apache-2.0
Requires: openstack.nose_plugin-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
openstack.nose_plugin - Nose plugin for openstack style test output
===================================================================

%package python
Summary: python components for the openstack.nose_plugin package.
Group: Default

%description python
python components for the openstack.nose_plugin package.


%prep
%setup -q -n openstack.nose_plugin-0.11

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
